function(simpl3_projects_preset is_msvc_runtime_lib_dynamic is_msvc_release_opt)
    if(MSVC)
        add_compile_options(/fp:fast)
        add_compile_options(/MP)
        #add_compile_options(/openmp)
        add_compile_options(/permissive-)
        add_compile_options(/sdl)
        add_compile_options(/utf-8)
        #add_compile_options(/Wall)
        #add_compile_options(/WX)
        add_compile_options(/Zc:__cplusplus)
        add_compile_options(/Zc:char8_t-)
        add_compile_options(/Zc:preprocessor)
        
        if(is_msvc_runtime_lib_dynamic)
            #add_compile_options(/MD$<$<CONFIG:Debug>:d>)
        else()
            add_compile_options(/MT$<$<CONFIG:Debug>:d>)
        endif()
        
        if(is_msvc_release_opt)
            add_compile_options($<$<CONFIG:Release>:/O2>)
            add_compile_options($<$<CONFIG:Release>:/Ob2>)
            add_compile_options($<$<CONFIG:Release>:/Oi>)
            add_compile_options($<$<CONFIG:Release>:/Ot>)
            add_compile_options($<$<CONFIG:Release>:/Oy>)
            add_compile_options($<$<CONFIG:Release>:/GL>)

            add_link_options($<$<CXX_COMPILER_ID:MSVC>:$<$<CONFIG:Release>:/LTCG>>)
        endif()
    endif()
    
    add_compile_definitions($<$<CXX_COMPILER_ID:MSVC>:_CRT_SECURE_NO_WARNINGS>)
    add_compile_definitions(PROJECT_NAME=${PROJECT_NAME})
    add_compile_definitions(CMAKE_PROJECT_NAME=${CMAKE_PROJECT_NAME})
    
    #set_property(GLOBAL PROPERTY USE_FOLDERS ON)
endfunction()

function(simpl3_option option_name option_value)
    if(ARGC GREATER 2)
        set(option_desc "${ARGV2}")
    else()
        set(option_desc "desc...")
    endif()
    
    option(${option_name} ${option_desc} ${option_value})
    if(${option_name})
        message(STATUS "`${option_name}` is 1, ${option_desc}")
        add_definitions(-D"${option_name}=1")
    else()
        add_definitions(-D"${option_name}=0")
        message(STATUS "`${option_name}` is 0, ${option_desc}")
    endif()
endfunction()